use master 
GO
CREATE DATABASE BAITHI;
DROP DATABASE BAITHI

USE BAITHI;
GO

-- Bảng NHACUNGCAP
CREATE TABLE NHACUNGCAP (
    MANCC CHAR(5) PRIMARY KEY,
    TENNCC NVARCHAR(50),
    QUOCGIA NVARCHAR(50),
    LOAINCC NVARCHAR(20)
);

-- Bảng DUOCPHAM
CREATE TABLE DUOCPHAM (
    MADP CHAR(5) PRIMARY KEY,
    TENDP NVARCHAR(50),
    LOAIDP NVARCHAR(20),
    GIA DECIMAL(10, 2)
);

-- Bảng PHIEUNHAP
CREATE TABLE PHIEUNHAP (
    SOPN CHAR(5) PRIMARY KEY,
    NGNHAP DATE,
    MANCC CHAR(5),
    LOAINHAP NVARCHAR(20),
    FOREIGN KEY (MANCC) REFERENCES NHACUNGCAP(MANCC)
);

-- Bảng CTPN
CREATE TABLE CTPN (
    SOPN CHAR(5),
    MADP CHAR(5),
    SOLUONG INT,
    PRIMARY KEY (SOPN, MADP),
    FOREIGN KEY (SOPN) REFERENCES PHIEUNHAP(SOPN),
    FOREIGN KEY (MADP) REFERENCES DUOCPHAM(MADP)
);


INSERT INTO NHACUNGCAP VALUES
('NCC01', N'Phuc Hung', N'Viet Nam', N'Thuong xuyen'),
('NCC02', N'J. B. Pharmaceuticals', N'India', N'Vang lai'),
('NCC03', N'Sapharco', N'Singapore', N'Vang lai');

INSERT INTO DUOCPHAM VALUES
('DP01', N'Thuoc ho PH', N'Siro', 120000),
('DP02', N'Zecuf Herbal CouchRemedy', N'Vien nen', 200000),
('DP03', N'Cotrim', N'Vien sui', 80000);

INSERT INTO PHIEUNHAP VALUES
('00001', '2017-11-22', 'NCC01', N'Noi dia'),
('00002', '2017-12-04', 'NCC03', N'Nhap khau'),
('00003', '2017-12-10', 'NCC02', N'Nhap khau');

INSERT INTO CTPN VALUES
('00001', 'DP01', 100),
('00001', 'DP02', 200),
('00003', 'DP03', 543);


ALTER TABLE DUOCPHAM
ADD CONSTRAINT CK_GIA_SIRO CHECK (
    NOT (LOAIDP = N'Siro' AND GIA <= 100000)
);

SELECT *
FROM PHIEUNHAP
WHERE YEAR(NGNHAP) = 2017 AND MONTH(NGNHAP) = 12
ORDER BY NGNHAP;

-- Bước 6: Tìm dược phẩm nhập số lượng nhiều nhất năm 2017
SELECT TOP 1 DP.TENDP, SUM(CT.SOLUONG) AS TOTAL_QUANTITY
FROM CTPN CT
JOIN PHIEUNHAP PN ON CT.SOPN = PN.SOPN
JOIN DUOCPHAM DP ON CT.MADP = DP.MADP
WHERE YEAR(PN.NGNHAP) = 2017
GROUP BY DP.TENDP
ORDER BY TOTAL_QUANTITY DESC;

-- Bước 7: Tìm dược phẩm chỉ có nhà cung cấp thường xuyên cung cấp
SELECT DP.TENDP
FROM DUOCPHAM DP
WHERE NOT EXISTS (
    SELECT 1
    FROM PHIEUNHAP PN
    JOIN NHACUNGCAP NC ON PN.MANCC = NC.MANCC
    WHERE NC.LOAINCC = N'Vang lai' AND DP.MADP IN (
        SELECT MADP FROM CTPN WHERE SOPN = PN.SOPN
    )
);
 

SELECT NC.TENNCC
FROM NHACUNGCAP NC
WHERE NOT EXISTS (
    SELECT 1
    FROM DUOCPHAM DP
    WHERE DP.GIA > 100000 AND NOT EXISTS (
        SELECT 1
        FROM PHIEUNHAP PN
        JOIN CTPN CT ON PN.SOPN = CT.SOPN
        WHERE PN.MANCC = NC.MANCC AND CT.MADP = DP.MADP AND YEAR(PN.NGNHAP) = 2017
    )
);
